### ISSUE TITLE
Turtle can't equip sword

### ISSUE THREAD

**Issue by MissPotato** [Shiranuit/Computeacube#1]
I unequipped a sword to enchant it, after enchanting I tried re-equipping the sword. For some reason, it errored out, so I crafted a new sword without enchants and tried that and it still wouldn't equip. I then tried crafting the named turtle together with the sword and that wouldn't work either.

**Comment by Shiranuit** [comment]
This fork doesn't allow you to equip an echanted sword but to use it

**Comment by MissPotato** [comment]
"but to use it" as in, I can use it from the inventory or?
